[package]
name = "thalmann"
version = "0.1.6"
edition = "2021"

[dependencies]
num = { version = "0.4.3", default-features = false, features = ["libm"] }

[features]
default = ["thalmann"]
thalmann = []
