/// Note: This example is AI-Generated by MS Copilot
use std::fs::File;
use std::io::Write;

use stdc_diving_algorithms::deco_algorithm::{
    DecoSettings, MVALUES, TISSUES, calc_deco_schedule,
};
use stdc_diving_algorithms::dive::{DiveMeasurement, DiveProfile};
use stdc_diving_algorithms::gas::{GasDensitySettings, MAX_PO2_DECO, NX50, NX100, TMX18_45};
use stdc_diving_algorithms::loadings_from_dive_profile;
use stdc_diving_algorithms::pressure_unit::{Pa, Pressure, msw};
use stdc_diving_algorithms::setup::{DINC, NUM_STOP_DEPTHS};
use stdc_diving_algorithms::gas::best_available_mix;

fn main() {
    // Build gases array: TMX18/45 (0), NX50 (1), NX100 (2)
    let gases = [TMX18_45, NX50, NX100];
    let gases_enabled = [true; 3];

    // Rates and durations in ms
    let descent_rate_m_per_min = 20.0_f32; // m/min
    let bottom_time_min = 25.0_f32; // minutes
    let ascent_rate_deep_m_per_min = 9.0_f32; // m/min from 55m to 21m
    let ascent_rate_shallow_m_per_min = 3.0_f32; // m/min from 21m to surface

    // Depths
    let surface = 0.0_f32;
    let bottom = 55.0_f32;
    let shallow_transition = 21.0_f32;

    // Compute times (ms)
    let descent_time_s = bottom / descent_rate_m_per_min * 60.0;
    let descent_ms = (descent_time_s * 1000.0) as usize;

    // Interpret `bottom_time_min` as the runtime (since start) when the bottom phase ends.
    let bottom_end_ms = (bottom_time_min * 60.0 * 1000.0) as usize;
    let bottom_ms = if bottom_end_ms > descent_ms {
        bottom_end_ms - descent_ms
    } else {
        0_usize
    };

    let ascent_deep_m = bottom - shallow_transition;
    let ascent_deep_time_s = ascent_deep_m / ascent_rate_deep_m_per_min * 60.0;
    let ascent_deep_ms = (ascent_deep_time_s * 1000.0) as usize;

    let ascent_shallow_time_s = shallow_transition / ascent_rate_shallow_m_per_min * 60.0;
    let ascent_shallow_ms = (ascent_shallow_time_s * 1000.0) as usize;

    // Measurements (M = 5)
    let t0 = 0_usize;
    let t1 = t0 + descent_ms;
    let t2 = t1 + bottom_ms;
    let t3 = t2 + ascent_deep_ms;
    let t4 = t3 + ascent_shallow_ms;

    let measurements = [
        DiveMeasurement {
            time_ms: t0,
            depth: msw::new(surface).to_pa(),
            gas: 0,
        },
        DiveMeasurement {
            time_ms: t1,
            depth: msw::new(bottom).to_pa(),
            gas: 0,
        },
        DiveMeasurement {
            time_ms: t2,
            depth: msw::new(bottom).to_pa(),
            gas: 0,
        },
        // DiveMeasurement {
        //     time_ms: t3,
        //     depth: msw::new(shallow_transition).to_pa(),
        //     gas: 1,
        // },
        // DiveMeasurement {
        //     time_ms: t4,
        //     depth: msw::new(surface).to_pa(),
        //     gas: 2,
        // },
    ];

    let profile: DiveProfile<Pa, f32, 3, 3> = DiveProfile {
        dive_id: 1,
        max_depth: msw::new(bottom).to_pa(),
        gases,
        measurements,
    };

    // Compute tissue loadings
    let loadings = loadings_from_dive_profile(&TISSUES, &profile, &MVALUES, msw::new(0.0).to_pa());

    // Compute deco schedule
    let deco_settings = DecoSettings {
        gas_density_settings: GasDensitySettings::Ignore,
        max_deco_po2: MAX_PO2_DECO.to_pa(),
    };

    let stops = match calc_deco_schedule::<{ NUM_STOP_DEPTHS - 1 }, 3>(
        &loadings,
        &gases,
        &gases_enabled,
        &deco_settings,
    ) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("No deco schedule: {}", e);
            return;
        }
    };

    // Print deco stops to console for debugging
    println!("Deco stops (depth m, duration s):");
    for s in stops.stops().iter() {
        let depth_m = s.depth().to_msw().to_f32();
        let dur_s = s.duration().as_secs_f32();
        println!("  depth={:.1}m dur={:.1}s", depth_m, dur_s);
    }

    // Report the first stop from the computed schedule.
    if let Some(fs) = stops.first_stop().map(|stop| stop.depth()) {
        println!("first stop candidate: {:.1}m", fs.to_msw().to_f32());
        let mix = best_available_mix(
            stdc_diving_algorithms::gas::MAX_PO2_DECO.to_pa(),
            fs.to_pa().into(),
            &gases,
            &gases_enabled,
            &loadings,
            false,
            &GasDensitySettings::Ignore,
        );
        println!("best_available_mix at first stop: {:?}", mix);
    } else {
        println!("no first stop candidate found in schedule");
    }

    // Create output directory and SVG
    let out_dir = "output";
    std::fs::create_dir_all(out_dir).expect("create output dir");
    let filename = format!("{}/sample_dive.svg", out_dir);
    let mut file = File::create(&filename).expect("create svg");

    let width = 1000.0;
    let height = 600.0;

    // margins to avoid clipping
    let left_margin = 60.0;
    let right_margin = 100.0;
    let top_margin = 50.0;
    let bottom_margin = 80.0;

    // Time range
    let total_ms = t4 as f32;

    // Depth range 0..bottom+5
    let max_depth = bottom + 5.0;

    let inner_width = width - left_margin - right_margin;
    let inner_height = height - top_margin - bottom_margin;

    let mut svg = String::new();
    svg.push_str(&format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{}\" height=\"{}\">\n",
        width, height
    ));

    // Background
    svg.push_str(&format!(
        "<rect width=\"100%\" height=\"100%\" fill=\"#ffffff\"/>\n"
    ));

    // Title
    svg.push_str(&format!("<text x=\"{:.1}\" y=\"24\" font-family=\"monospace\" font-size=\"14\">Sample dive profile: 55m 25min</text>\n", left_margin));

    // Draw profile polyline points
    let mut points: Vec<(f32, f32)> = Vec::new();
    for m in &profile.measurements {
        let x = left_margin + (m.time_ms as f32 / total_ms) * inner_width;
        let depth_m = m.depth.to_msw().to_f32();
        let y = top_margin + (depth_m / max_depth) * inner_height;
        points.push((x, y));
    }

    // Draw grid: vertical (time) every 5 minutes, horizontal (depth) every DINC
    // vertical time grid (every 5 minutes)
    let grid_time_step_ms: f32 = 5.0 * 60.0 * 1000.0; // 5 minutes
    let mut gt: f32 = 0.0;
    while gt <= total_ms {
        let x = left_margin + (gt / total_ms) * inner_width;
        let y1 = top_margin;
        let y2 = top_margin + inner_height;
        svg.push_str(&format!(
            "<line x1=\"{:.1}\" y1=\"{:.1}\" x2=\"{:.1}\" y2=\"{:.1}\" stroke=\"#000000\" stroke-width=\"1\" stroke-opacity=\"0.08\"/>\n",
            x, y1, x, y2
        ));
        // label each vertical grid line with exact time H:MM:SS
        let t_secs = (gt / 1000.0).round() as u64;
        let hours = t_secs / 3600;
        let mins = (t_secs % 3600) / 60;
        let secs = t_secs % 60;
        let time_label = format!("{}:{:02}:{:02}", hours, mins, secs);
        svg.push_str(&format!(
            "<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"10\" font-family=\"monospace\">{}</text>\n",
            x - 24.0,
            y2 + 26.0,
            time_label
        ));
        gt += grid_time_step_ms;
    }

    // horizontal depth grid every DINC meters and label each line with depth (m)
    let dinc_m = DINC.to_msw().to_f32();
    let mut d: f32 = 0.0;
    while d <= max_depth {
        let y = top_margin + (d / max_depth) * inner_height;
        let x1 = left_margin;
        let x2 = left_margin + inner_width;
        svg.push_str(&format!(
            "<line x1=\"{:.1}\" y1=\"{:.1}\" x2=\"{:.1}\" y2=\"{:.1}\" stroke=\"#000000\" stroke-width=\"1\" stroke-opacity=\"0.08\"/>\n",
            x1, y, x2, y
        ));
        // label depth at left of plot
        svg.push_str(&format!("<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"10\" font-family=\"monospace\">{:.0}m</text>\n", x1-36.0, y+4.0, d));
        d += dinc_m;
    }

    // time axis ticks and labels (5 ticks)
    for i in 0..5 {
        let t = (i as f32) * total_ms / 4.0;
        let x = left_margin + (t / total_ms) * inner_width;
        let y1 = top_margin + inner_height + 6.0;
        let y2 = top_margin + inner_height + 14.0;
        svg.push_str(&format!("<line x1=\"{:.1}\" y1=\"{:.1}\" x2=\"{:.1}\" y2=\"{:.1}\" stroke=\"#000000\" stroke-width=\"1\"/>\n", x, y1, x, y2));
        // format time always as H:MM:SS
        let t_secs = (t / 1000.0).round() as u64;
        let hours = t_secs / 3600;
        let mins = (t_secs % 3600) / 60;
        let secs = t_secs % 60;
        let time_label = format!("{}:{:02}:{:02}", hours, mins, secs);
        svg.push_str(&format!(
            "<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"12\" font-family=\"monospace\">{}</text>\n",
            x - 30.0,
            y2 + 12.0,
            time_label
        ));
    }

    // polyline
    svg.push_str("<polyline fill=\"none\" stroke=\"#0077cc\" stroke-width=\"2\" points=\"");
    for (x, y) in &points {
        svg.push_str(&format!("{:.1},{:.1} ", x, y));
    }
    svg.push_str("\"/>\n");

    // Mark gas switches
    for (i, m) in profile.measurements.iter().enumerate() {
        let (x, y) = points[i];
        svg.push_str(&format!(
            "<circle cx=\"{:.1}\" cy=\"{:.1}\" r=\"6\" fill=\"#ff5500\"/>\n",
            x, y
        ));
        // Format time always as H:MM:SS
        let t_secs = (m.time_ms / 1000) as u64;
        let hours = t_secs / 3600;
        let mins = (t_secs % 3600) / 60;
        let secs = t_secs % 60;
        let time_label = format!("{}:{:02}:{:02}", hours, mins, secs);
        // Gas as O2/He (percentages rounded)
        let gas_mix = gases[m.gas];
        let fo2 = (gas_mix.fo2() * 100.0).round() as i32;
        let fhe = (gas_mix.fhe() * 100.0).round() as i32;
        let gas_label = format!("{}/{}", fo2, fhe);
        svg.push_str(&format!("<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"12\" font-family=\"monospace\">{} {}</text>\n", x+8.0, y-8.0, time_label, gas_label));
        // depth label at point
        svg.push_str(&format!("<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"10\" font-family=\"monospace\">{:.0}m</text>\n", x+8.0, y+8.0, m.depth.to_msw().to_f32()));
    }

    // Draw deco stops from StopSchedule
    let stop_arr = stops.stops();
    for s in stop_arr.iter() {
        if s.duration().is_zero() {
            continue;
        }
        let depth_m = s.depth().to_msw().to_f32();
        // Map depth to y
        let y = top_margin + (depth_m / max_depth) * inner_height;
        // Map duration to width (proportional to total_ms)
        let w = (s.duration().as_millis() as f32 / total_ms) * (inner_width);
        let x = width - right_margin + 10.0; // place deco bars in right margin
        svg.push_str(&format!("<rect x=\"{:.1}\" y=\"{:.1}\" width=\"{:.1}\" height=\"12\" fill=\"#88cc88\" stroke=\"#006600\"/>\n", x, y-6.0, w));
        svg.push_str(&format!("<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"10\" font-family=\"monospace\">Depth {:.0}m: {:.0}s</text>\n", x + w + 6.0, y+4.0, depth_m, s.duration().as_secs_f32()));
    }

    svg.push_str("</svg>");

    file.write_all(svg.as_bytes()).expect("write svg");

    println!("Wrote {}", filename);
}
