/// Note: This example is AI-Generated by MS Copilot
use std::println;

use stdc_diving_algorithms::dive::{DiveMeasurement, DiveProfile};
use stdc_diving_algorithms::gas::{NX50, NX100, TMX18_45};
use stdc_diving_algorithms::pressure_unit::{Pa, Pressure, msw};

fn main() {
    // Build gases array: TMX18/45 (0), NX50 (1), NX100 (2)
    let gases = [TMX18_45, NX50, NX100];

    // Rates and durations in ms
    let descent_rate_m_per_min = 20.0_f32; // m/min
    let bottom_time_min = 25.0_f32; // minutes
    let ascent_rate_deep_m_per_min = 9.0_f32; // m/min from 55m to 21m
    let ascent_rate_shallow_m_per_min = 3.0_f32; // m/min from 21m to surface

    // Depths
    let surface = 0.0_f32;
    let bottom = 55.0_f32;
    let shallow_transition = 21.0_f32;

    // Compute times (ms)
    let descent_time_s = bottom / descent_rate_m_per_min * 60.0;
    let descent_ms = (descent_time_s * 1000.0) as usize;

    let bottom_ms = (bottom_time_min * 60.0 * 1000.0) as usize;

    let ascent_deep_m = bottom - shallow_transition;
    let ascent_deep_time_s = ascent_deep_m / ascent_rate_deep_m_per_min * 60.0;
    let ascent_deep_ms = (ascent_deep_time_s * 1000.0) as usize;

    let ascent_shallow_time_s = shallow_transition / ascent_rate_shallow_m_per_min * 60.0;
    let ascent_shallow_ms = (ascent_shallow_time_s * 1000.0) as usize;

    // Measurements (M = 5)
    // t0: surface at start
    let t0 = 0_usize;
    // t1: end descent at bottom
    let t1 = t0 + descent_ms;
    // t2: end bottom
    let t2 = t1 + bottom_ms;
    // t3: reach 21m (end of deep ascent)
    let t3 = t2 + ascent_deep_ms;
    // t4: surface (end shallow ascent)
    let t4 = t3 + ascent_shallow_ms;

    let measurements = [
        DiveMeasurement {
            time_ms: t0,
            depth: msw::new(surface).to_pa(),
            gas: 0,
        },
        DiveMeasurement {
            time_ms: t1,
            depth: msw::new(bottom).to_pa(),
            gas: 0,
        },
        DiveMeasurement {
            time_ms: t2,
            depth: msw::new(bottom).to_pa(),
            gas: 0,
        },
        DiveMeasurement {
            time_ms: t3,
            depth: msw::new(shallow_transition).to_pa(),
            gas: 1,
        },
        DiveMeasurement {
            time_ms: t4,
            depth: msw::new(surface).to_pa(),
            gas: 2,
        },
    ];

    let profile: DiveProfile<Pa, f32, 3, 5> = DiveProfile {
        dive_id: 1,
        max_depth: msw::new(bottom).to_pa(),
        gases,
        measurements,
    };

    println!("Sample dive profile (55m 25min)\n{:#?}", profile);
    println!(
        "Times (ms): descent={} bottom={} ascent_deep={} ascent_shallow={} total={}",
        descent_ms, bottom_ms, ascent_deep_ms, ascent_shallow_ms, t4
    );
}
